# Generated by Django 5.2.1 on 2025-05-10 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afrinet', '0002_payment_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='voucher',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
