# Generated by Django 5.2.1 on 2025-08-12 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afrinet', '0003_customuser_password_reset_expires_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='reset_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='reset_code_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='reset_code_expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
