# Generated by Django 5.2.1 on 2025-05-10 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afrinet', '0005_rename_start_time_session_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='payment',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='vouchers', to='afrinet.payment'),
        ),
    ]
