# Generated by Django 5.2.1 on 2025-05-12 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afrinet', '0006_voucher_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='expires_at',
            field=models.DateTimeField(auto_created=True, blank=True, null=True),
        ),
    ]
