# Generated by Django 5.2.1 on 2025-05-12 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('afrinet', '0007_alter_session_expires_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session',
            old_name='expires_at',
            new_name='end_time',
        ),
        migrations.RenameField(
            model_name='voucher',
            old_name='expires_at',
            new_name='end_time',
        ),
    ]
