# Generated by Django 5.2.1 on 2025-05-12 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('afrinet', '0008_rename_expires_at_session_end_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session',
            old_name='voucher',
            new_name='voucher_code',
        ),
    ]
