# Generated by Django 5.2.1 on 2025-05-12 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afrinet', '0009_rename_voucher_session_voucher_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='duration',
        ),
        migrations.AddField(
            model_name='package',
            name='duration_unit',
            field=models.CharField(choices=[('min', 'Minutes'), ('hour', 'Hours'), ('day', 'Days')], default='min', max_length=20),
        ),
        migrations.AddField(
            model_name='package',
            name='duration_value',
            field=models.IntegerField(default=1),
        ),
    ]
