# Generated by Django 5.2.1 on 2025-05-14 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('afrinet', '0014_payment_voucher_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='voucher_code',
        ),
    ]
