# Generated by Django 5.2.1 on 2025-05-16 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afrinet', '0015_remove_payment_voucher_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payment',
            name='is_successful',
            field=models.BooleanField(default=False),
        ),
    ]
