# Generated by Django 5.2.1 on 2025-05-16 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afrinet', '0016_payment_is_finished_payment_is_successful'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='afrinet.payment'),
        ),
    ]
