# Generated by Django 5.2.1 on 2025-05-16 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('afrinet', '0017_session_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session',
            old_name='user_phone',
            new_name='phone_number',
        ),
    ]
