# Generated by Django 5.2.1 on 2025-07-05 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afrinet', '0019_remove_user_phone_number_user_expiry_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='is_checked',
            field=models.BooleanField(default=False),
        ),
    ]
