# Generated by Django 5.2.1 on 2025-07-05 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afrinet', '0020_payment_is_checked'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='phone_number',
            new_name='phone',
        ),
        migrations.RemoveField(
            model_name='session',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='voucher',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='session',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='voucher',
            name='phone',
            field=models.CharField(default='', max_length=50),
        ),
    ]
