# Generated by Django 5.2.1 on 2025-07-08 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afrinet', '0021_rename_phone_number_payment_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='package_name',
            field=models.CharField(default='P1', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='package_id',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
