# Generated by Django 5.2.1 on 2025-07-08 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afrinet', '0022_package_package_name_alter_package_package_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='package_name',
            field=models.CharField(default='P1', max_length=50),
        ),
    ]
