# Generated by Django 5.2.1 on 2025-07-10 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afrinet', '0028_alter_package_package_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='MikroTikDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ip', models.CharField(max_length=15)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=100)),
                ('port', models.CharField(default='8728', max_length=5)),
                ('status', models.CharField(choices=[('Online', 'Online'), ('Offline', 'Offline')], default='Offline', max_length=10)),
                ('lastUpdate', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
