# Generated by Django 5.2.1 on 2025-07-10 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afrinet', '0029_mikrotikdevice'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
